name: g4
description: "Gemma 4 On-Device AI Chat Application for Android."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_gemma: ^0.15.3
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  shared_preferences: ^2.5.3
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
